# Generated by Django 6.0.5 on 2026-05-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_roomapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomapplication',
            old_name='member',
            new_name='applicant',
        ),
        migrations.AlterField(
            model_name='roomapplication',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='chat.chatroom'),
        ),
    ]
