x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./app:/workspace/app
  env_file:
    - ./app/.env
  restart: unless-stopped

services:
  spreadtalk:
    <<: *common
    ports:
      - "8000:8000"
    working_dir: /workspace
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug --reload