services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spreadtalk_web
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    command: daphne -b 0.0.0.0 -p 8000 messenger.asgi:application
    volumes:
      - ./app:/app
    develop:
      watch:
        - action: rebuild
          path: ./app/requirements.txt
    restart: unless-stopped