# Generated by Django 6.0.1 on 2026-01-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField()),
                ('content', models.TextField()),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
